name: Generate Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: francilenegs1996

          outputs: |
            dist/github-contribution-grid.svg?color_snake=transparent&color_dots=#44475A,#1D5C32,#278C4B,#36C96B,#50FA7B

      - name: Publish contribution grid
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
